package com.example.libraryproject;

import android.content.Intent;
import android.content.SharedPreferences;
import android.database.Cursor;
import android.os.Bundle;
import android.text.TextUtils;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import com.example.libraryproject.DatabaseHelper;
import com.example.libraryproject.databinding.ActivityLoginBinding; // Generated by ViewBinding

public class LoginActivity extends AppCompatActivity {

    private ActivityLoginBinding binding;
    private DatabaseHelper dbHelper;
    private SharedPreferences sharedPreferences;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivityLoginBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        dbHelper = new DatabaseHelper(this);
        sharedPreferences = getSharedPreferences("LoginPrefs", MODE_PRIVATE);

        // Check if user is already logged in (from SplashActivity)
        if (sharedPreferences.getBoolean("isLoggedIn", false)) {
            redirectToHome();
            return; // Important: finish this activity if already logged in
        }

        binding.buttonLogin.setOnClickListener(v -> {
            String username = binding.editTextUsername.getText().toString().trim();
            String password = binding.editTextPassword.getText().toString().trim();

            if (TextUtils.isEmpty(username) || TextUtils.isEmpty(password)) {
                Toast.makeText(LoginActivity.this, "Please enter username and password", Toast.LENGTH_SHORT).show();
            } else {
                Cursor cursor = dbHelper.getUser(username, password);
                if (cursor != null && cursor.moveToFirst()) {
                    // User found, credentials are correct
                    int userId = cursor.getInt(cursor.getColumnIndexOrThrow(DatabaseHelper.COL_USER_ID));
                    String role = cursor.getString(cursor.getColumnIndexOrThrow(DatabaseHelper.COL_ROLE));
                    String phone = cursor.getString(cursor.getColumnIndexOrThrow(DatabaseHelper.COL_PHONE));

                    // Save login status and user info to SharedPreferences
                    SharedPreferences.Editor editor = sharedPreferences.edit();
                    editor.putBoolean("isLoggedIn", true);
                    editor.putInt("userId", userId);
                    editor.putString("username", username);
                    editor.putString("role", role);
                    editor.putString("phone", phone);
                    editor.apply();

                    Toast.makeText(LoginActivity.this, "Login successful!", Toast.LENGTH_SHORT).show();
                    redirectToHome();
                } else {
                    Toast.makeText(LoginActivity.this, "Invalid username or password", Toast.LENGTH_SHORT).show();
                }
                if (cursor != null) {
                    cursor.close();
                }
            }
        });

        binding.textViewRegister.setOnClickListener(v -> {
            // Navigate to RegisterActivity
            Intent intent = new Intent(LoginActivity.this, RegisterActivity.class);
            startActivity(intent);
        });
    }

    private void redirectToHome() {
        String role = sharedPreferences.getString("role", "Student");
        Intent intent;
        if ("Admin".equals(role)) {
            intent = new Intent(LoginActivity.this, AdminHomeActivity.class); // Create this activity later
        } else {
            intent = new Intent(LoginActivity.this, StudentHomeActivity.class); // Create this activity later
        }
        startActivity(intent);
        finish(); // Close LoginActivity
    }
}