package com.example.libraryproject;

import android.content.Intent;
import android.os.Bundle;
import android.text.TextUtils;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import com.example.libraryproject.DatabaseHelper;
import com.example.libraryproject.LoginActivity;
import com.example.libraryproject.databinding.ActivityRegisterBinding; // Generated by ViewBinding

public class RegisterActivity extends AppCompatActivity {

    private ActivityRegisterBinding binding;
    private DatabaseHelper dbHelper;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivityRegisterBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        dbHelper = new DatabaseHelper(this);

        binding.buttonRegister.setOnClickListener(v -> {
            String username = binding.editTextUsername.getText().toString().trim();
            String phone = binding.editTextPhone.getText().toString().trim();
            String password = binding.editTextPassword.getText().toString().trim();
            String role = binding.radioAdmin.isChecked() ? "Admin" : "Student";

            if (TextUtils.isEmpty(username) || TextUtils.isEmpty(password)) {
                Toast.makeText(RegisterActivity.this, "Username and Password cannot be empty", Toast.LENGTH_SHORT).show();
            } else {
                if (dbHelper.checkUsernameExists(username)) {
                    Toast.makeText(RegisterActivity.this, "Username already exists. Please choose another.", Toast.LENGTH_SHORT).show();
                } else {
                    boolean isAdded = dbHelper.addUser(username, password, phone, role);
                    if (isAdded) {
                        Toast.makeText(RegisterActivity.this, "Registration successful!", Toast.LENGTH_SHORT).show();
                        // Redirect back to Login screen
                        Intent intent = new Intent(RegisterActivity.this, LoginActivity.class);
                        startActivity(intent);
                        finish(); // Close RegisterActivity
                    } else {
                        Toast.makeText(RegisterActivity.this, "Registration failed. Please try again.", Toast.LENGTH_SHORT).show();
                    }
                }
            }
        });

        binding.textViewLogin.setOnClickListener(v -> {
            // Navigate back to LoginActivity
            Intent intent = new Intent(RegisterActivity.this, LoginActivity.class);
            startActivity(intent);
            finish(); // Close RegisterActivity
        });
    }
}