package com.example.libraryproject;

import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.os.Handler;

import androidx.appcompat.app.AppCompatActivity;

import com.example.libraryproject.databinding.ActivitySplashBinding; // Generated by ViewBinding

public class SplashActivity extends AppCompatActivity {

    private ActivitySplashBinding binding; // Declare ViewBinding object
    private static final int SPLASH_TIME_OUT = 1500; // 1.5 seconds

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivitySplashBinding.inflate(getLayoutInflater()); // Initialize ViewBinding
        setContentView(binding.getRoot()); // Set the root view from binding

        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                // Check if user is already logged in
                SharedPreferences preferences = getSharedPreferences("LoginPrefs", MODE_PRIVATE);
                boolean isLoggedIn = preferences.getBoolean("isLoggedIn", false);

                Intent i;
                if (isLoggedIn) {
                    // If logged in, go to HomeActivity (or appropriate activity based on role)
                    // For now, let's assume it goes to LoginActivity, you'll change this later
                    // based on user role
                    i = new Intent(SplashActivity.this, LoginActivity.class);
                } else {
                    // If not logged in, go to LoginActivity
                    i = new Intent(SplashActivity.this, LoginActivity.class);
                }
                startActivity(i);
                finish(); // Close this activity
            }
        }, SPLASH_TIME_OUT);
    }
}
